name: flutter_quiz_exam
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # intl
  intl: ^0.19.0
  # json annotation
  json_annotation: ^4.5.0
  # riverpods
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  # Hooks flutter
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  # Router
  go_router: ^14.2.8
  # API
  http: ^1.2.2
  # Firebase
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.1
  # Dialog
  quickalert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # Generate files using dart code. We will use it to generate the fromJson/toJson functions
  build_runner: ^2.1.11
  # Used together with json_serializable to generate fromJson/toJson functions
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/quiz-logo.png
    - assets/images/gameOver.png
    - assets/images/thinking.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
