// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4yv-xa2BHhdejKRpm-ZhBn-KJihgEcZo',
    appId: '1:174526462889:web:49b6733c23b5777569a2b8',
    messagingSenderId: '174526462889',
    projectId: 'flutter-quiz-exam',
    authDomain: 'flutter-quiz-exam.firebaseapp.com',
    storageBucket: 'flutter-quiz-exam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMoIBIPJ9VqeRqWAVIgTwxoTWpADCmutY',
    appId: '1:174526462889:android:4bce2328afa2c8bc69a2b8',
    messagingSenderId: '174526462889',
    projectId: 'flutter-quiz-exam',
    storageBucket: 'flutter-quiz-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt6Fejpd-Kw3v2wkmq1eMKzq-jqa1SpF0',
    appId: '1:174526462889:ios:49ad9b99e9edbfca69a2b8',
    messagingSenderId: '174526462889',
    projectId: 'flutter-quiz-exam',
    storageBucket: 'flutter-quiz-exam.appspot.com',
    iosBundleId: 'com.example.flutterQuizExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt6Fejpd-Kw3v2wkmq1eMKzq-jqa1SpF0',
    appId: '1:174526462889:ios:49ad9b99e9edbfca69a2b8',
    messagingSenderId: '174526462889',
    projectId: 'flutter-quiz-exam',
    storageBucket: 'flutter-quiz-exam.appspot.com',
    iosBundleId: 'com.example.flutterQuizExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4yv-xa2BHhdejKRpm-ZhBn-KJihgEcZo',
    appId: '1:174526462889:web:ee4656a192dff1d769a2b8',
    messagingSenderId: '174526462889',
    projectId: 'flutter-quiz-exam',
    authDomain: 'flutter-quiz-exam.firebaseapp.com',
    storageBucket: 'flutter-quiz-exam.appspot.com',
  );
}
